#### Loading libraries needed ####
if (!require("binman")) install.packages("binman")
if (!require("caret")) install.packages("caret")
if (!require("dashboardthemes")) install.packages("dashboardthemes")
if (!require("data.table")) install.packages("data.table")
if (!require("DBI")) install.packages("DBI")
if (!require("dbplyr")) install.packages("dbplyr")
if (!require("devtools")) install.packages("devtools")
if (!require("dplyr")) install.packages("dplyr")
if (!require("forcats")) install.packages("forcats")
if (!require("fuzzyjoin")) install.packages("fuzzyjoin")
if (!require("httr")) install.packages("httr")
if (!require("janitor")) install.packages("janitor")
if (!require("kableExtra")) install.packages("kableExtra")
if (!require("lubridate")) install.packages("lubridate")
if (!require("magrittr")) install.packages("magrittr")
if (!require("miceadds")) install.packages("miceadds")
if (!require("netstat")) install.packages("netstat")
if (!require("plotly")) install.packages("plotly")
if (!require("reactable")) install.packages("reactable")
if (!require("reactablefmtr")) install.packages("reactablefmtr")
if (!require("rlist")) install.packages("rlist")
if (!require("RMariaDB")) install.packages("RMariaDB")
if (!require("rsconnect")) install.packages("rsconnect")
if (!require("RSelenium")) install.packages("RSelenium")
if (!require("rvest")) install.packages("rvest")
if (!require("r2d3")) install.packages("r2d3")
if (!require("shiny")) install.packages("shiny")
if (!require("shinyalert")) install.packages("shinyalert")
if (!require("shinyjs")) install.packages("shinyjs")
if (!require("shinycssloaders")) install.packages("shinycssloaders")
if (!require("shinydashboard")) install.packages("shinydashboard")
if (!require("shinythemes")) install.packages("shinythemes")
if (!require("stringr")) install.packages("stringr")
if (!require("tibble")) install.packages("tibble")
if (!require("tidyr")) install.packages("tidyr")
if (!require("TTR")) install.packages("TTR")
if (!require("viridis")) install.packages("viridis")
if (!require("xfun")) install.packages("xfun")
if (!require("XML")) install.packages("XML")
if (!require("xml2")) install.packages("xml2")


library(binman)
library(caret)
library(dashboardthemes)
library(data.table)
library(DBI)
library(dbplyr)
library(dplyr)
library(forcats)
library(fuzzyjoin)
library(httr)
library(janitor)
library(kableExtra)
library(lubridate)
library(miceadds)
library(netstat)
library(plotly)
library(reactable)
library(reactablefmtr)
library(rlist)
library(RMariaDB)
library(rsconnect)
library(RSelenium)
library(rvest)
library(r2d3)
library(shiny)
library(shinyalert)
library(shinyjs)
library(shinycssloaders)
library(shinydashboard)
library(shinythemes)
library(stringr)
library(tibble)
library(tidyr)
library(TTR)
library(viridis)
library(XML)
library(xml2)

# Source script containing all API keys needed
source("API_keys.R")
# Source all R-files in the External Functions folder
source.all("Functions/External Functions/", grepstring="\\.R")
# Source all R-files in the Functions folder
source.all("Functions/", grepstring="\\.R")
# Source all in data subfolders
source.all("Data/Mapping Tables/", grepstring="\\.R")
# Source all R files in the Shiny folder
source.all("Shiny/", grepstring="\\.R")
# list all RData files in the Data folder
rdata_files <- paste0("Data/", list.files("Data/", pattern="*.RData"))
# load all the RData object into the global environment
lapply(rdata_files, load, .GlobalEnv)

